name: CI
on: [push, pull_request]

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci
      - run: npm run lint

      # Ensure script has exec bit (belt & suspenders)
      - run: chmod +x scripts/smoke.sh

      # Start API in the background for smoke tests
      - name: Start server
        run: |
          HOST=127.0.0.1 PORT=13080 NODE_ENV=development \
          node src/server.js &

      # Optional: wait a moment (or swap for a health check loop)
      - run: sleep 1

      - name: Run smoke test
        run: npm run smoke
