name: CI

on:
  push:
  pull_request:

jobs:
  node:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      HOST: 127.0.0.1
      PORT: 13800
      NODE_ENV: development
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      NO_PROXY: "localhost,127.0.0.1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install OS deps (jq for smoke.sh)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Install deps
        run: npm ci

      - name: Start server (background) and capture logs
        shell: bash
        run: |
          npm run start > server.log 2>&1 &
          echo $! > server.pid
          # optional: live tail so logs show in the step output too
          tail -n +1 -f server.log &
          echo $! > tail.pid

      - name: Wait for health (max 45s)
        shell: bash
        run: |
          for i in {1..45}; do
            if curl -fsS "http://127.0.0.1:${PORT}/api/v1/health" >/dev/null; then
              echo "Server is healthy"
              exit 0
            fi
            sleep 1
          done
          echo "::error::Health check timed out"
          exit 1

      - name: Smoke test
        run: npm run smoke

      - name: Lint
        run: npm run lint

      - name: Upload server log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: server-log
          path: server.log

      - name: Cleanup
        if: always()
        shell: bash
        run: |
          if [ -f tail.pid ]; then kill "$(cat tail.pid)" 2>/dev/null || true; fi
          if [ -f server.pid ]; then kill "$(cat server.pid)" 2>/dev/null || true; fi
          pkill -f "node src/server.js" 2>/dev/null || true
          lsof -i :"${PORT}" || true
