name: CI
on:
  push:
  pull_request:

jobs:
  node:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Start server (background)
        env:
          HOST: 127.0.0.1
          PORT: 13880
          NODE_ENV: development
          http_proxy: ""
          https_proxy: ""
          HTTP_PROXY: ""
          HTTPS_PROXY: ""
        run: |
          node src/server.js > server.log 2>&1 &
          echo $! > server.pid
          echo "PID=$(cat server.pid)"

      - name: Wait for health
        run: |
          for i in {1..40}; do
            if curl -fsS "http://127.0.0.1:13880/api/v1/health" >/dev/null; then
              echo "healthy"; break
            fi
            sleep 0.5
          done
          # one last assert
          curl -fsS "http://127.0.0.1:13880/api/v1/health"

      - name: Smoke test
        run: bash scripts/smoke.sh

      - name: Lint
        run: npm run lint

      - name: Show server log (always)
        if: always()
        run: |
          echo "----- server.log -----"
          tail -n +1 server.log || true

      - name: Stop server (always)
        if: always()
        run: |
          kill "$(cat server.pid)" 2>/dev/null || true
