name: CI

on:
  push:
  pull_request:

jobs:
  node:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    # Job-wide environment (no duplicates)
    env:
      HOST: 127.0.0.1
      PORT: 13800
      NODE_ENV: development
      NO_PROXY: 127.0.0.1,localhost
      http_proxy: ""
      https_proxy: ""
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      ALL_PROXY: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Start server
        run: |
          nohup npm run start > server.log 2>&1 &
          echo $! > server.pid

      - name: Wait for health
        run: |
          for i in {1..60}; do
            code=$(curl -sS -o /dev/null -w "%{http_code}" http://127.0.0.1:13800/api/v1/health || true)
            if [ "$code" = "200" ]; then
              echo "Server is up."
              exit 0
            fi
            sleep 1
          done
          echo "Timed out waiting for server"
          echo "---- server.log (tail) ----"
          tail -n 200 server.log || true
          exit 1

      - name: Smoke test
        run: npm run smoke

      - name: Lint
        run: npm run lint

      - name: Print server log on failure
        if: failure()
        run: |
          echo "---- server.log (tail) ----"
          tail -n 200 server.log || true
          echo "---- ps aux | grep node ----"
          ps aux | grep node || true

      - name: Stop server
        if: always()
        run: |
          if [ -f server.pid ]; then kill $(cat server.pid) || true; fi
