name: CI

on:
  push:
  pull_request:

jobs:
  node:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Start server
        run: |
          node src/server.js &
          echo $! > .server_pid
        env:
          HOST: 127.0.0.1
          PORT: 13800
          NODE_ENV: development

      - name: Wait for server (healthcheck)
        run: |
          for i in {1..30}; do
            if curl -fsS http://127.0.0.1:13800/api/v1/health >/dev/null; then
              echo "Server is up"; exit 0
            fi
            sleep 1
          done
          echo "Server never became healthy"; exit 1

      - name: Smoke tests
        run: npm run smoke

      - name: Lint
        run: npm run lint

      - name: Stop server
        if: always()
        run: |
          kill -9 "$(cat .server_pid)" 2>/dev/null || true
